### ISSUE TITLE
開発環境：account.htmlからアップロードした写真がuserのmodelと紐づかない

### ISSUE THREAD

**Issue by shin-carpediem** [shin-carpediem/Djamazon#53]
エラー内容：
TypeError at /is_img/
render() missing 1 required positional argument: 'template_name'
＊app/views.pyの関数 is_img の、451行目でエラー発生

やりたい事：
account.htmlからアップロードして保存された写真データを表示するまでの流れで、上のエラーをなくしたい。

場所：
[https://github.com/shin-carpediem/Djamazon/blob/master/app/views.py](url)
445行目~454行目

**Comment by yuta-kaset** [comment]
@login_required
def is_img(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        user.is_img = request.FILES.get('is_img')
        user.save()
        return redirect('app:account')
        # return render(request, 'app/account.html')
    is_img = AddUserImgForm()
    return render(request, 'app/account.html', {'is_img': is_img})
