### ISSUE TITLE
javasript：touch.jsのchangelevelValueElemの値がundefinedしか返さない

### ISSUE THREAD

**Issue by shin-carpediem** [shin-carpediem/Djamazon#54]
エラー内容：
typing.min.js:1 Uncaught TypeError: Cannot set property 'textContent' of null
    at setWord (typing.min.js:1)
    at HTMLDocument.<anonymous> (typing.min.js:1)

やりたい事：
その下の行のswitch文に正しく数値としてchangelevelValueElemを返したい。

場所：
[https://github.com/shin-carpediem/Djamazon/blob/master/static/js/games/touch.js](url)
155行目

**Comment by yuta-kaset** [comment]
const changelevelElem = document.getElementById("changeLevel");
  const changelevelValueElem = changelevelElem.value;
  const currentValueElem = document.getElementById("current-value");
  const changeLevel = (level) => {
    new Game(level);
  }

  // 現在の値をspanに埋め込む関数
  const setCurrentValue = (val) => {
    currentValueElem.innerText = val;
  }; // inputイベント時に値をセットする関数

  const rangeOnChange = (e) => {
    const level = e.target.value;
    changeLevel(level)
    setCurrentValue(level);
  };

  window.onload = () => {
    // スライダー変化時にイベントを発火
    changelevelElem.addEventListener("input", rangeOnChange);
    setCurrentValue(changelevelValueElem);

**Comment by yuta-kaset** [comment]
class Board {
    constructor(game) {
      this.game = game;
      this.panels = [];
      for (let i = 0; i < this.game.getLevel() ** 2; i++) {
        this.panels.push(new Panel(this.game));
      }
      this.setup();
    }

    setup() {
      const board = document.getElementById("touch-board");
      board.innerHTML = ''
      this.panels.forEach((panel) => {
        // クラスのプロパティに外部から直接指定するのは避けた方が良いとされているので、
        // メソッド経由で呼び出す。（=オブジェクト思考のカプセル化）
        board.appendChild(panel.getEl());
      });
    }
